## **Numpy Arrays**

In [1]:
# We have to import the numpy library first
import numpy as np

In [2]:
# 1D
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# 2D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
# 3D
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [5]:
#dtype
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [6]:
np.array([1,2,3], dtype=int)

array([1, 2, 3])

In [7]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [8]:
# np.arange
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [9]:
# Reshaping Arrays
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [10]:
# np ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
# np random
np.random.random((3,4))

array([[0.25224009, 0.27431651, 0.11101517, 0.80147187],
       [0.63574415, 0.43807775, 0.10991536, 0.29599972],
       [0.4929145 , 0.84345351, 0.23810222, 0.85096964]])

In [12]:
# np linspace
np.linspace(-10, 10, 10, dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])